export const ADD_DENTIST = "addDentist"
export const ADD_ASSISTANT = "addAssistant"
export const ADD_PATIENT = "addPatient"
export const SICK_DENTIST = "sickDentist"
export const SICK_ASSISTANT = "sickAssistant"
export const SICK_PATIENT = "sickPatient"
export const MAKE_APPOINTMENT = "makeAppointment"
export const REMOVE_APPOINTMENT = "removeAppointment"